name: Release on push to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run check
        run: cargo check
      - name: Run build
        run: cargo build --release -v
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          # name: ${{ github.job }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}-${{matrix.os}}
          files: | 
            target/release/diceware
            target/release/diceware.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
