name: Release builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run check
        run: cargo check
      - name: Run build
        run: cargo build --release -v
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ${{ github.job }}
          files: | 
            target/release/diceware
            target/release/diceware.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
