name: Release builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:      
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo check
    - name: Build release
      run: cargo build --release -vv
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: |
          target/release/diceware
          target/release/diceware(.exe|.deb|.app)?
          !target/release/diceware.(pdb|d$)
