name: Release Ubuntu builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo check
    - name: Build release
      run: cargo build --release -v
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: target/release/diceware